name: Lint and check types

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install poetry
        run: |
          pip install pipx
          pipx install poetry

      - name: Install dependencies
        run: |
          poetry install

      - name: Linting code by flake8
        run: |
          poetry run flake8 --show-source --statistics

      - name: Check types by pyright
        run: |
          poetry run pyright